---
abstract: 'Structured data file IO with OO paradigm'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Exception::Class: 1.23
  Test::More: 0.74
  Text::Diff: 1.37
  utf8: 1.06
configure_requires:
  Module::Build: 0.32
  version: 0.74
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-DataClass
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  File::DataClass:
    file: lib/File/DataClass.pm
    version: v0.18.6
  File::DataClass::Cache:
    file: lib/File/DataClass/Cache.pm
    version: v0.18.1
  File::DataClass::Constants:
    file: lib/File/DataClass/Constants.pm
    version: v0.18.4
  File::DataClass::Constraints:
    file: lib/File/DataClass/Constraints.pm
    version: v0.18.1
  File::DataClass::Exception:
    file: lib/File/DataClass/Exception.pm
    version: v0.18.4
  File::DataClass::Exception::Simple:
    file: lib/File/DataClass/Exception/Simple.pm
    version: v0.18.4
  File::DataClass::Functions:
    file: lib/File/DataClass/Functions.pm
    version: v0.18.1
  File::DataClass::HashMerge:
    file: lib/File/DataClass/HashMerge.pm
    version: v0.18.1
  File::DataClass::IO:
    file: lib/File/DataClass/IO.pm
    version: v0.18.1
  File::DataClass::List:
    file: lib/File/DataClass/List.pm
    version: v0.18.1
  File::DataClass::Result:
    file: lib/File/DataClass/Result.pm
    version: v0.18.1
  File::DataClass::ResultSet:
    file: lib/File/DataClass/ResultSet.pm
    version: v0.18.1
  File::DataClass::ResultSource:
    file: lib/File/DataClass/ResultSource.pm
    version: v0.18.1
  File::DataClass::Schema:
    file: lib/File/DataClass/Schema.pm
    version: v0.18.1
  File::DataClass::Storage:
    file: lib/File/DataClass/Storage.pm
    version: v0.18.1
  File::DataClass::Storage::Any:
    file: lib/File/DataClass/Storage/Any.pm
    version: v0.18.1
  File::DataClass::Storage::JSON:
    file: lib/File/DataClass/Storage/JSON.pm
    version: v0.18.1
  File::DataClass::Storage::XML:
    file: lib/File/DataClass/Storage/XML.pm
    version: v0.18.1
  File::DataClass::Storage::XML::Bare:
    file: lib/File/DataClass/Storage/XML/Bare.pm
    version: v0.18.1
  File::DataClass::Storage::XML::Simple:
    file: lib/File/DataClass/Storage/XML/Simple.pm
    version: v0.18.1
  File::DataClass::TraitFor::PrependingErrorLeader:
    file: lib/File/DataClass/TraitFor/PrependingErrorLeader.pm
    version: v0.18.5
  File::DataClass::TraitFor::ThrowingExceptions:
    file: lib/File/DataClass/TraitFor/ThrowingExceptions.pm
    version: v0.18.2
  File::DataClass::TraitFor::TracingStacks:
    file: lib/File/DataClass/TraitFor/TracingStacks.pm
    version: v0.18.3
recommends:
  App::cpanminus: 1.6005
  Pod::Markdown: 1.322
requires:
  CHI: 0.33
  Cache::FastMmap: 1.36
  Carp: 0
  Class::Null: 1.09
  Devel::StackTrace: 1.26
  File::Path: 2.08
  File::Temp: 0.2
  Hash::Merge: 0.08
  IO::Dir: 1.05
  IO::File: 1.13
  JSON: 2.16
  Moose: 2.0801
  MooseX::ClassAttribute: 0.27
  MooseX::Types: 0.25
  MooseX::Types::Common: 0.001002
  MooseX::Types::LoadableClass: 0.007
  Scalar::Util: 1.18
  Sub::Exporter: 0.982
  Sub::Exporter::Progressive: 0.001006
  Try::Tiny: 0.06
  XML::Bare: 0.3
  XML::DTD: 0.09
  XML::Simple: 2.14
  namespace::autoclean: 0.13
  namespace::clean: 0.22
  overload: 1.04
  perl: 5.01
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-DataClass
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.18.6
