---
abstract: 'Structured data file IO with OO paradigm'
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
build_requires:
  Exception::Class: 1.23
  Moose: 2.0402
  Test::More: 0.74
  Text::Diff: 1.37
  utf8: 1.06
configure_requires:
  Module::Build: 0.32
  Moose: 2.0402
  version: 0.74
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-DataClass
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  File::DataClass:
    file: lib/File/DataClass.pm
    version: v0.8.357
  File::DataClass::Cache:
    file: lib/File/DataClass/Cache.pm
    version: v0.8.351
  File::DataClass::Constants:
    file: lib/File/DataClass/Constants.pm
    version: v0.8.351
  File::DataClass::Constraints:
    file: lib/File/DataClass/Constraints.pm
    version: v0.8.351
  File::DataClass::Exception:
    file: lib/File/DataClass/Exception.pm
    version: v0.8.351
  File::DataClass::HashMerge:
    file: lib/File/DataClass/HashMerge.pm
    version: v0.8.351
  File::DataClass::IO:
    file: lib/File/DataClass/IO.pm
    version: v0.8.351
  File::DataClass::List:
    file: lib/File/DataClass/List.pm
    version: v0.8.351
  File::DataClass::Result:
    file: lib/File/DataClass/Result.pm
    version: v0.8.351
  File::DataClass::ResultSet:
    file: lib/File/DataClass/ResultSet.pm
    version: v0.8.351
  File::DataClass::ResultSource:
    file: lib/File/DataClass/ResultSource.pm
    version: v0.8.351
  File::DataClass::ResultSource::WithLanguage:
    file: lib/File/DataClass/ResultSource/WithLanguage.pm
    version: v0.8.351
  File::DataClass::Schema:
    file: lib/File/DataClass/Schema.pm
    version: v0.8.351
  File::DataClass::Schema::WithLanguage:
    file: lib/File/DataClass/Schema/WithLanguage.pm
    version: v0.8.351
  File::DataClass::Storage:
    file: lib/File/DataClass/Storage.pm
    version: v0.8.351
  File::DataClass::Storage::JSON:
    file: lib/File/DataClass/Storage/JSON.pm
    version: v0.8.351
  File::DataClass::Storage::WithLanguage:
    file: lib/File/DataClass/Storage/WithLanguage.pm
    version: v0.8.351
  File::DataClass::Storage::XML:
    file: lib/File/DataClass/Storage/XML.pm
    version: v0.8.351
  File::DataClass::Storage::XML::Bare:
    file: lib/File/DataClass/Storage/XML/Bare.pm
    version: v0.8.351
  File::DataClass::Storage::XML::Simple:
    file: lib/File/DataClass/Storage/XML/Simple.pm
    version: v0.8.351
  File::DataClass::Util:
    file: lib/File/DataClass/Util.pm
    version: v0.8.351
  File::Gettext:
    file: lib/File/Gettext.pm
    version: v0.8.351
  File::Gettext::Constants:
    file: lib/File/Gettext/Constants.pm
    version: v0.8.351
  File::Gettext::Storage::MO:
    file: lib/File/Gettext/Storage/MO.pm
    version: v0.8.351
  File::Gettext::Storage::PO:
    file: lib/File/Gettext/Storage/PO.pm
    version: v0.8.351
  File::MailAlias:
    file: lib/File/MailAlias.pm
    version: v0.8.351
  File::MailAlias::Storage:
    file: lib/File/MailAlias/Storage.pm
    version: v0.8.351
  File::MealMaster:
    file: lib/File/MealMaster.pm
    version: v0.8.351
  File::MealMaster::Result:
    file: lib/File/MealMaster/Result.pm
    version: v0.8.351
  File::MealMaster::Storage:
    file: lib/File/MealMaster/Storage.pm
    version: v0.8.351
  File::UnixAuth:
    file: lib/File/UnixAuth.pm
    version: v0.8.351
  File::UnixAuth::Result:
    file: lib/File/UnixAuth/Result.pm
    version: v0.8.351
  File::UnixAuth::Storage:
    file: lib/File/UnixAuth/Storage.pm
    version: v0.8.351
requires:
  CHI: 0.33
  Cache::FastMmap: 1.36
  Carp: 0
  Class::Null: 1.09
  Date::Format: 2.22
  Encode: 2.12
  Exception::Class: 1.23
  File::Path: 2.08
  File::Temp: 0.2
  Hash::Merge: 0.08
  IO::Dir: 1.05
  IO::File: 1.13
  IPC::Cmd: 0.68
  IPC::SRLock: v0.7.0
  JSON: 2.16
  Lingua::EN::NameParse: 1.28
  MealMaster: 0.28
  Moose: 2.0402
  MooseX::ClassAttribute: 0.26
  Scalar::Util: 1.18
  Sub::Exporter: 0.982
  Template: 2.18
  Template::Stash: 2.9
  Text::Wrap: 2005.082401
  Try::Tiny: 0.06
  XML::Bare: 0.3
  XML::DTD: 0.09
  XML::Simple: 2.14
  namespace::autoclean: 0.13
  namespace::clean: 0.22
  overload: 1.04
  perl: 5.01
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-DataClass
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: 0.8.357
