---
abstract: 'Structured data file IO with OO paradigm'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  File::pushd: '1.00'
  Module::Build: '0.4004'
  Path::Tiny: '0.013'
  Test::Deep: '0.108'
  Test::Requires: '0.06'
  Text::Diff: '1.37'
  version: '0.88'
configure_requires:
  Module::Build: '0.4004'
  version: '0.88'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-DataClass
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  File::DataClass:
    file: lib/File/DataClass.pm
    version: v0.35.1
  File::DataClass::Cache:
    file: lib/File/DataClass/Cache.pm
    version: v0.35.1
  File::DataClass::Constants:
    file: lib/File/DataClass/Constants.pm
    version: v0.35.1
  File::DataClass::Exception:
    file: lib/File/DataClass/Exception.pm
    version: v0.35.1
  File::DataClass::Functions:
    file: lib/File/DataClass/Functions.pm
    version: v0.35.1
  File::DataClass::HashMerge:
    file: lib/File/DataClass/HashMerge.pm
    version: v0.35.1
  File::DataClass::IO:
    file: lib/File/DataClass/IO.pm
    version: v0.35.1
  File::DataClass::List:
    file: lib/File/DataClass/List.pm
    version: v0.35.1
  File::DataClass::Result:
    file: lib/File/DataClass/Result.pm
    version: v0.35.1
  File::DataClass::ResultSet:
    file: lib/File/DataClass/ResultSet.pm
    version: v0.35.1
  File::DataClass::ResultSource:
    file: lib/File/DataClass/ResultSource.pm
    version: v0.35.1
  File::DataClass::Schema:
    file: lib/File/DataClass/Schema.pm
    version: v0.35.1
  File::DataClass::Storage:
    file: lib/File/DataClass/Storage.pm
    version: v0.35.1
  File::DataClass::Storage::Any:
    file: lib/File/DataClass/Storage/Any.pm
    version: v0.35.1
  File::DataClass::Storage::JSON:
    file: lib/File/DataClass/Storage/JSON.pm
    version: v0.35.1
  File::DataClass::Types:
    file: lib/File/DataClass/Types.pm
    version: v0.35.1
requires:
  CHI: '0.58'
  Cache::FastMmap: '1.40'
  Class::Method::ModifiersX::Augment: '0.001'
  Class::Null: '2.101420'
  File::Path: '2.08'
  Hash::Merge: '0.12'
  JSON::MaybeXS: '1.001000'
  Module::Runtime: '0.013'
  Moo: '1.004002'
  MooX::ClassStash: '0.005'
  Try::Tiny: '0.18'
  Type::Tiny: '0.030'
  Unexpected: v0.22.0
  namespace::clean: '0.24'
  namespace::sweep: '0.006'
  perl: '5.010001'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-DataClass
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.35.1
